# -*- coding: utf-8 -*-
"""SistemRekomendasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hsyE4PYFQCfeP9wy8PFMU_nrbG4ipXX
"""

# ============================================================
# HYBRID RECOMMENDATION SYSTEM — E-Commerce Product Intelligence
# Google Colab Ready | Python 3.10+
# ============================================================
# Arsitektur hybrid:
#   1. Collaborative Filtering (ALS implicit)   → pengguna dengan riwayat
#   2. Content-Based Filtering (TF-IDF + cosine) → cold-start produk
#   3. Session-Based (popularitas + konteks sesi) → cold-start pengguna
#   4. Hybrid Combiner (weighted score fusion)   → output akhir
# ============================================================

# ─── Install dependencies ───────────────────────────
!pip install implicit scikit-learn pandas numpy scipy tqdm --quiet

import kagglehub
import os
import pandas as pd
import numpy as np
import scipy.sparse as sp
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from collections import defaultdict
from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")

print("✅ Libraries loaded.")

# ─── Load dataset ───────────────────────────────────
path = kagglehub.dataset_download("anujsaha0123456789/e-commerce-product-intelligence-dataset")

# Sesuaikan path jika perlu
USERS_PATH       = os.path.join(path, "users.csv")
PRODUCTS_PATH    = os.path.join(path, "products.csv")
INTERACTIONS_PATH= os.path.join(path, "interactions.csv")
SESSIONS_PATH    = os.path.join(path, "sessions.csv")
PURCHASES_PATH   = os.path.join(path, "purchases.csv")
REVIEWS_PATH     = os.path.join(path, "reviews.csv")

users        = pd.read_csv(USERS_PATH)
products     = pd.read_csv(PRODUCTS_PATH)
interactions = pd.read_csv(INTERACTIONS_PATH)
sessions     = pd.read_csv(SESSIONS_PATH)
purchases    = pd.read_csv(PURCHASES_PATH)
reviews      = pd.read_csv(REVIEWS_PATH)

print(f"✅ Data loaded:")
print(f"   users        : {users.shape}")
print(f"   products     : {products.shape}")
print(f"   interactions : {interactions.shape}")
print(f"   sessions     : {sessions.shape}")
print(f"   purchases    : {purchases.shape}")
print(f"   reviews      : {reviews.shape}")

# ─── CELL 4: Preprocessing ──────────────────────────────────

# 4.1 — Bobot implicit per tipe interaksi
INTERACTION_WEIGHTS = {
    "view"               : 1.0,
    "click"              : 2.0,
    "add_to_wishlist"    : 3.0,
    "add_to_cart"        : 4.0,
    "remove_from_wishlist": -1.0,
    "remove_from_cart"   : -2.0,
}

interactions["weight"] = interactions["interaction_type"].map(INTERACTION_WEIGHTS).fillna(1.0)

# 4.2 — Aggregate skor per (user, product)
agg = (
    interactions
    .groupby(["user_id", "product_id"])["weight"]
    .sum()
    .reset_index()
    .rename(columns={"weight": "implicit_score"})
)
# Clip agar skor tidak negatif
agg["implicit_score"] = agg["implicit_score"].clip(lower=0)

# 4.3 — Encode user & product ID ke integer
user_enc    = LabelEncoder()
product_enc = LabelEncoder()

agg["user_idx"]    = user_enc.fit_transform(agg["user_id"])
agg["product_idx"] = product_enc.fit_transform(agg["product_id"])

n_users    = agg["user_idx"].max() + 1
n_products = agg["product_idx"].max() + 1

print(f"✅ Preprocessing selesai.")
print(f"   Users aktif    : {n_users}")
print(f"   Produk aktif   : {n_products}")
print(f"   Interaksi valid: {len(agg)}")

# ─── CELL 5: Sparse matrix untuk CF ─────────────────────────

# User-item sparse matrix (CSR)
ui_matrix = sp.csr_matrix(
    (agg["implicit_score"].values,
     (agg["user_idx"].values, agg["product_idx"].values)),
    shape=(n_users, n_products)
)

print(f"✅ Sparse matrix: {ui_matrix.shape}, density: {ui_matrix.nnz / (n_users * n_products):.4%}")

# ─── CELL 6: Collaborative Filtering — ALS (implicit) ━━━━━━━

try:
    import implicit
    USE_ALS = True
except ImportError:
    USE_ALS = False
    print("☃  Library 'implicit' tidak ditemukan.")

if USE_ALS:
    from implicit.als import AlternatingLeastSquares

    # Inisialisasi model
    als_model = AlternatingLeastSquares(
        factors=64,
        regularization=0.1,
        iterations=30,
        use_gpu=False,
        random_state=42,
    )

    # implicit expects [user x item] for modern versions, but historically [item x user].
    als_model.fit(ui_matrix)
    print(f"✅ ALS model trained. User factors: {als_model.user_factors.shape[0]}, Item factors: {als_model.item_factors.shape[0]}")

def cf_recommend(user_id, top_n=10):
    if not USE_ALS or 'als_model' not in globals():
        return {}

    if user_id not in user_enc.classes_:
        return {}

    user_idx = user_enc.transform([user_id])[0]

    # Check if user index is valid for the trained model
    if user_idx >= als_model.user_factors.shape[0]:
        return {}

    # Pass the user's row from the matrix to the recommend function
    ids, scores = als_model.recommend(
        user_idx, ui_matrix[user_idx], N=top_n * 2, filter_already_liked_items=False
    )

    result = {}
    valid_mask = ids < len(product_enc.classes_)
    valid_ids = ids[valid_mask]
    valid_scores = scores[valid_mask]

    for pid_idx, score in zip(valid_ids, valid_scores):
        pid = product_enc.inverse_transform([pid_idx])[0]
        result[pid] = float(score)
    return result

# ─── CELL 7: Content-Based Filtering — TF-IDF ━━━━━━━━━━━━━━━

# 7.1 — Bangun fitur teks produk
def build_product_text(row):
    parts = [
        str(row.get("product_name", "")),
        str(row.get("category", "")),
        str(row.get("subcategory", "")),
        str(row.get("brand", "")),
        str(row.get("description", "")),
    ]
    return " ".join(p for p in parts if p and p != "nan")

products["content_text"] = products.apply(build_product_text, axis=1)

# 7.2 — Tambahkan teks ulasan ke produk jika tersedia
if "review_text" in reviews.columns and "product_id" in reviews.columns:
    review_agg = (
        reviews.groupby("product_id")["review_text"]
        .apply(lambda x: " ".join(x.dropna().astype(str)))
        .reset_index()
        .rename(columns={"review_text": "review_corpus"})
    )
    # FIX: Drop existing review_corpus if it exists to avoid merge naming conflicts
    if "review_corpus" in products.columns:
        products = products.drop(columns=["review_corpus"])

    products = products.merge(review_agg, on="product_id", how="left")
    products["content_text"] = products["content_text"] + " " + products["review_corpus"].fillna("")

# 7.3 — TF-IDF vectorizer
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True,
)
tfidf_matrix = tfidf.fit_transform(products["content_text"])

print(f"✅ TF-IDF matrix: {tfidf_matrix.shape}")

# Index produk untuk lookup
product_id_to_idx = {pid: i for i, pid in enumerate(products["product_id"])}
product_idx_to_id = {i: pid for pid, i in product_id_to_idx.items()}


def cb_recommend(product_ids_liked, top_n=10):
    """
    Content-Based: berikan daftar product_id yang pernah disukai pengguna,
    kembalikan produk serupa. Mengembalikan dict {product_id: score}.
    """
    valid_ids = [p for p in product_ids_liked if p in product_id_to_idx]
    if not valid_ids:
        return {}

    indices = [product_id_to_idx[p] for p in valid_ids]
    user_profile = np.asarray(tfidf_matrix[indices].mean(axis=0))  # rata-rata vektor

    # Hitung cosine similarity terhadap semua produk
    sim_scores = cosine_similarity(user_profile, tfidf_matrix).flatten()

    # Exclude produk yang sudah dilihat
    for idx in indices:
        sim_scores[idx] = 0.0

    top_indices = np.argsort(sim_scores)[::-1][:top_n]
    return {product_idx_to_id[i]: float(sim_scores[i]) for i in top_indices if sim_scores[i] > 0}

# ─── CELL 8: Session-Based — Popularitas & Konteks ──────────

# 8.1 — Hitung popularitas produk (digunakan untuk cold-start)
product_popularity = (
    interactions
    .groupby("product_id")["weight"]
    .sum()
    .reset_index()
    .rename(columns={"weight": "popularity_score"})
)
product_popularity["popularity_score"] = MinMaxScaler().fit_transform(
    product_popularity[["popularity_score"]]
)
popularity_dict = dict(zip(
    product_popularity["product_id"],
    product_popularity["popularity_score"]
))

# 8.2 — Hitung konversi per produk (purchase count)
if "product_id" in purchases.columns:
    purchase_counts = purchases["product_id"].value_counts().to_dict()
    max_purchase = max(purchase_counts.values()) if purchase_counts else 1
    conversion_score = {pid: cnt / max_purchase for pid, cnt in purchase_counts.items()}
else:
    conversion_score = {}


def session_recommend(session_context=None, top_n=10, exclude_ids=None):
    """
    Session-Based: gabungkan skor popularitas + konversi.
    session_context: dict opsional berisi {'device': 'mobile', 'referrer': 'social_media'}
    Mengembalikan dict {product_id: score}.
    """
    exclude_ids = set(exclude_ids or [])
    scores = {}
    for pid in popularity_dict:
        if pid in exclude_ids:
            continue
        pop  = popularity_dict.get(pid, 0.0)
        conv = conversion_score.get(pid, 0.0)
        scores[pid] = 0.6 * pop + 0.4 * conv

    # Opsional: boost berdasarkan kategori populer di device tertentu
    if session_context and "device" in session_context:
        device = session_context["device"]
        if device in sessions.columns:
            device_sessions = sessions[
                sessions["device"] == device
            ]
            if "product_id" in interactions.columns:
                device_interactions = interactions[
                    interactions["session_id"].isin(device_sessions.get("session_id", []))
                ]
                device_pop = device_interactions["product_id"].value_counts()
                if len(device_pop) > 0:
                    device_pop = device_pop / device_pop.max()
                    for pid, score in device_pop.items():
                        if pid not in exclude_ids:
                            scores[pid] = scores.get(pid, 0.0) + 0.1 * score

    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return dict(sorted_scores[:top_n])

# ─── CELL 9: Hybrid Combiner ────────────────────────────────

# Bobot tiap komponen (bisa di-tune)
WEIGHTS = {
    "cf"      : 0.50,  # collaborative filtering
    "cb"      : 0.30,  # content-based
    "session" : 0.20,  # session/popularity
}


def normalize_scores(score_dict):
    """Min-max normalisasi skor dalam rentang [0, 1]."""
    if not score_dict:
        return {}
    vals = list(score_dict.values())
    min_v, max_v = min(vals), max(vals)
    if max_v == min_v:
        return {k: 1.0 for k in score_dict}
    return {k: (v - min_v) / (max_v - min_v) for k, v in score_dict.items()}


def hybrid_recommend(user_id, session_context=None, top_n=10, train_history=None):
    if 'user_enc' not in globals(): return pd.DataFrame()
    is_known_user = (user_id in user_enc.classes_) if USE_ALS else False

    # PERUBAHAN: Gunakan train_history jika ada (saat evaluasi),
    # jika tidak, gunakan seluruh riwayat (saat live production)
    if train_history is not None:
        user_history = set(train_history)
    else:
        user_history = set(
            interactions.loc[interactions["user_id"] == user_id, "product_id"].tolist()
        )

    # ── Collaborative Filtering ──────────────────────────────
    if is_known_user:
        cf_scores = cf_recommend(user_id, top_n=top_n * 3)
    else:
        cf_scores = {}

    # ── Content-Based ────────────────────────────────────────
    liked_products = list(user_history) if user_history else []
    cb_scores = cb_recommend(liked_products, top_n=top_n * 3) if liked_products else {}

    # ── Session / Popularitas ────────────────────────────────
    session_scores = session_recommend(
        session_context=session_context,
        top_n=top_n * 3,
        exclude_ids=user_history,
    )

    # ── Normalisasi ──────────────────────────────────────────
    cf_norm      = normalize_scores(cf_scores)
    cb_norm      = normalize_scores(cb_scores)
    session_norm = normalize_scores(session_scores)

    # Sesuaikan bobot jika user cold-start
    w_cf      = WEIGHTS["cf"]      if is_known_user else 0.0
    w_cb      = WEIGHTS["cb"]      if liked_products else 0.0
    w_session = WEIGHTS["session"]

    # Re-normalisasi bobot agar total = 1
    total_w = w_cf + w_cb + w_session
    if total_w == 0:
        total_w = 1.0
    w_cf      /= total_w
    w_cb      /= total_w
    w_session /= total_w

    # ── Fusion ──────────────────────────────────────────────
    all_products = set(cf_norm) | set(cb_norm) | set(session_norm)
    all_products -= user_history  # exclude yang sudah dilihat

    fused = {}
    for pid in all_products:
        score = (
            w_cf      * cf_norm.get(pid, 0.0) +
            w_cb      * cb_norm.get(pid, 0.0) +
            w_session * session_norm.get(pid, 0.0)
        )
        fused[pid] = {
            "hybrid_score"  : round(score, 4),
            "score_cf"      : round(cf_norm.get(pid, 0.0), 4),
            "score_cb"      : round(cb_norm.get(pid, 0.0), 4),
            "score_session" : round(session_norm.get(pid, 0.0), 4),
        }

    # Sort & ambil top_n
    top_items = sorted(fused.items(), key=lambda x: x[1]["hybrid_score"], reverse=True)[:top_n]

    # Gabungkan dengan info produk
    result_rows = []
    for pid, scores_dict in top_items:
        prod_info = products[products["product_id"] == pid]
        if prod_info.empty:
            name, cat, brand = pid, "–", "–"
        else:
            row = prod_info.iloc[0]
            name  = row.get("product_name", pid)
            cat   = row.get("category", "–")
            brand = row.get("brand", "–")

        result_rows.append({
            "product_id"    : pid,
            "product_name"  : name,
            "category"      : cat,
            "brand"         : brand,
            **scores_dict,
        })

    return pd.DataFrame(result_rows)

# ─── CELL 10: Evaluasi — Hit Rate & NDCG ────────────────────

def ndcg_at_k(recommended_items, ground_truth_items, k):
    """Calculates NDCG@k"""
    dcg = 0.0
    idcg = 0.0

    for i, item in enumerate(recommended_items[:k]):
        if item in ground_truth_items:
            dcg += 1.0 / np.log2(i + 2)

    for i in range(min(k, len(ground_truth_items))):
        idcg += 1.0 / np.log2(i + 2)

    return dcg / idcg if idcg > 0 else 0.0

def evaluate_model(test_interactions, n_users_eval=200, top_k=10):
    results = {"hit_rate": [], "ndcg": [], "user_type": []}

    user_ids = test_interactions["user_id"].unique()
    np.random.seed(42)
    sample_users = np.random.choice(user_ids, size=min(n_users_eval, len(user_ids)), replace=False)

    for uid in tqdm(sample_users, desc="Evaluating"):
        user_data = test_interactions[test_interactions["user_id"] == uid].sort_values("timestamp") \
            if "timestamp" in test_interactions.columns \
            else test_interactions[test_interactions["user_id"] == uid]

        if len(user_data) < 3: # Bisa dinaikkan ke 5 atau 10 jika ingin sampel lebih matang
            continue

        split = int(len(user_data) * 0.8)

        # PERUBAHAN: Pisahkan train dan test secara eksplisit
        train_data = user_data.iloc[:split]
        test_data  = user_data.iloc[split:]

        train_history = set(train_data["product_id"].tolist())
        ground_truth  = set(test_data["product_id"].tolist())

        is_known = (uid in user_enc.classes_) if USE_ALS else False

        # PERUBAHAN: Kirimkan train_history agar ground truth tidak ikut terhapus
        recs_df  = hybrid_recommend(uid, top_n=top_k, train_history=train_history)
        rec_ids  = recs_df["product_id"].tolist() if not recs_df.empty else []

        hit  = 1 if any(r in ground_truth for r in rec_ids) else 0
        ndcg = ndcg_at_k(rec_ids, ground_truth, k=top_k)

        results["hit_rate"].append(hit)
        results["ndcg"].append(ndcg)
        results["user_type"].append("known" if is_known else "cold-start")

    # ... (bagian print hasil tetap sama) ...
    df_results = pd.DataFrame(results)
    print("\n📊 Hasil Evaluasi Model Hybrid")
    print(f"  Hit Rate@{top_k}          : {df_results['hit_rate'].mean():.4f}")
    print(f"  NDCG@{top_k}              : {df_results['ndcg'].mean():.4f}")
    return df_results

# ─── CELL 11: Contoh penggunaan ─────────────────────────────

print("\n" + "=" * 55)
print("  DEMO: Hybrid Recommendation System")
print("=" * 55)

# Ambil satu user yang punya riwayat (known user)
known_users = agg["user_id"].unique()
demo_user_known = known_users[0]

print(f"\n🔹 Known user: {demo_user_known}")
recs_known = hybrid_recommend(
    user_id=demo_user_known,
    session_context={"device": "mobile", "referrer": "organic_search"},
    top_n=10,
)
print(recs_known[["product_name", "category", "brand", "hybrid_score",
                   "score_cf", "score_cb", "score_session"]].to_string(index=False))

# Ambil satu user yang tidak ada di riwayat interaksi (cold-start)
all_user_ids = users["user_id"].unique()
cold_start_candidates = [u for u in all_user_ids if u not in set(known_users)]
demo_user_cold = cold_start_candidates[0] if cold_start_candidates else "UNKNOWN_USER_999"

print(f"\n🔹 Cold-start user: {demo_user_cold}")
recs_cold = hybrid_recommend(
    user_id=demo_user_cold,
    session_context={"device": "desktop"},
    top_n=10,
)
print(recs_cold[["product_name", "category", "brand", "hybrid_score",
                  "score_cf", "score_cb", "score_session"]].to_string(index=False))

# ─── CELL 12: Evaluasi (opsional, butuh beberapa menit) ─────
# FIX: Strict validation of user indices against the actual ui_matrix shape

# Calculate how many users the model actually knows from the training matrix
n_trained_users = ui_matrix.shape[0]

# We only want user_ids that map to an index < n_trained_users
all_encoded_ids = user_enc.transform(user_enc.classes_)
valid_mask = all_encoded_ids < n_trained_users
valid_user_ids = user_enc.classes_[valid_mask]

# Filter interactions to only these valid users
eval_interactions = interactions[interactions['user_id'].isin(valid_user_ids)]

print(f"Evaluating {min(300, len(valid_user_ids))} users out of {len(valid_user_ids)} valid trained users.")
eval_results = evaluate_model(eval_interactions, n_users_eval=300, top_k=10)

# ─── CELL 13: Simpan hasil rekomendasi ke CSV ────────────────

output_file = "recommendations_sample.csv"
recs_known["user_id"] = demo_user_known
recs_cold["user_id"]  = demo_user_cold

all_recs = pd.concat([recs_known, recs_cold], ignore_index=True)
all_recs.to_csv(output_file, index=False)
print(f"\n✅ Hasil disimpan ke '{output_file}'")